### ISSUE TITLE
update of freescout fails

### ISSUE THREAD

**Issue by BrianGilbert** [tiredofit/docker-freescout#7]
Using the in app update link at /system/status I get a dialogue with the following:

```
Error occured. Please try again or try another update method
```

Installation using recommended containers for nginx-proxy and letsencrypt as per docs.

**Comment by tiredofit** [comment]
I don't believe In app update will work until I put more effort into understanding how that process works.
I've updated the image to pull the latest 1.3.4 release however. Should be up on Docker Hub shortly.

**Comment by BrianGilbert** [comment]
Confirming latest image now built with 1.3.3, can we catch up realtime somewhere to work through getting real time update working?

**Comment by BrianGilbert** [comment]
Looking at the update code I'm going to guess that git might be required..?

https://github.com/freescout-helpdesk/freescout/blob/533a482d2cbc8af819966a76bbe2596548d37242/config/self-update.php

**Comment by BrianGilbert** [comment]
created an issue to find out the self update requirements https://github.com/freescout-helpdesk/freescout/issues/300

**Comment by tiredofit** [comment]
The way this image is designed it that it won't do an auto update properly, as there are no volumes to export, ie the files that it downloads to auto update will disappear upon container restart.

One could try exporting the /www/freescout dir and putting the files in there, however I opted not to build that one as I build other images due to the rapid development happening with Freescout. I'll consider it, and likely revert the Dockerfile more closer to my other images for easier management. 

In the short term, if you notice a new version released, it's easy to update the image locally by altering the environment variable and rebuilding the image while you wait for me to update it on the Docker Hub.

**Comment by BrianGilbert** [comment]
@tiredofit does this mean that installed plugins would get blown away as part of an update as well?

**Comment by tiredofit** [comment]
I believe so. I wrote this pre plugin capability of Freescout, more so of a kick the tires image. I need to get some time in me to rework this so it can support these sort of extras. I have built lots of images much more complex than this and have an idea on how to do it in the past, it's just a matter of time on my end - I'm moonlighting this stuff and put more effort into the images I'm actively using in production in my organization and Freescout hasn't quite made it to full usage yet. I wouldn't mind meeting up live as you mentioned to work through the auto update system in the future.

**Comment by tiredofit** [comment]
Hi @BrianGilbert 
When you updated to my latest image, can you tell me if your installation just worked as is, or did you have to go through a web interface to update the database?

**Comment by BrianGilbert** [comment]
@tiredofit sorry, I can't recall as I was stopping starting and blowing things away a lot at the time..

**Comment by tiredofit** [comment]
I've got a development build right now that will allow for custom Modules with the present way of building and also give the option to export the actual source and let customizations happen. I have to let Docker Hub build `tiredofit/alpine:3.10` and `tiredofit/nginx-php-fpm/7.3` which seems to rebuild about 40 other images. Once they are all complete I be able to get this development build up for you to test.

**Comment by tiredofit** [comment]
If you could though help with getting me to understand if you can do an in place upgrade with one of my older images to the :latest without having to delete the database that will help as I can build in an automatic upgrade of the schema as well. Cursory looks at the auto update source code don't show any DB migrations occurring during the pull of data and I'm not the most familiar with artisan/laravel which may be able to detect a new version and execute the upgrades in the background. Either way I can force it, I just don't know if my force technique also deletes user data at this time. I'm doing this blind right now..

**Comment by BrianGilbert** [comment]
@tiredofit 

- installed docker-freescout 0.10, configured some settings..
- docker-compose down
- updated my docker-compose.yml to use latest tag
- restarted app using ddocker-composee up -d
- logged in a 1.3.3 shown in footer, in app update fails
- visited /system/tools and clicked migrate DB, response was "Nothing to migrate."

note: needed to clear cache at /system/tools for menus to work properly.

**Comment by BrianGilbert** [comment]
Did the same but from 0.8..

![Tools - FreeScout - Vivaldi 2019-08-07 12-38-01](https://user-images.githubusercontent.com/114017/62590604-403f0d00-b910-11e9-8dd0-1773b9effc98.png)

**Comment by tiredofit** [comment]
I'll take a good peek at this in the morning, I suppose I'm going to stop having to do this blind and get my own install working again.

**Comment by BrianGilbert** [comment]
I'f your wanting to run update programmatically the script mentioned here may help https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout

**Comment by BrianGilbert** [comment]
Resolved as of 1.0

**Comment by vikasprogrammer** [comment]
I am still getting this 

<img width="310" alt="Screenshot 2020-07-21 at 10 51 19 AM" src="https://user-images.githubusercontent.com/1262327/88016258-ab451c00-cb40-11ea-94f9-994011719fa6.png">
