### ISSUE TITLE
Can't fetch emails over IMAP

### ISSUE THREAD

**Issue by BrianGilbert** [tiredofit/docker-freescout#8]
```
[2019-07-31 14:29:10] Mailbox: Tech Support
[2019-07-31 14:29:10] Error: imap_open(): Couldn't open stream {imap.gmail.com:993/imap/ssl}. Certificate failure for imap.gmail.com: self signed certificate: /OU=No SNI provided; please fix your client./CN=invalid2.invalid; File: /www/html/vendor/webklex/laravel-imap/src/IMAP/Client.php (230)
[2019-07-31 14:29:10] Fetching finished
```

Installation using recommended nginx-proxy and ssl containers, using a modified version of the docker-compose.yml to start everything up.

```
version: '2'

services:

  freescout-app:
    image: tiredofit/freescout
    container_name: freescout-app
    links:
      - freescout-db
    volumes:
      - ./logs/:/www/logs
    environment:
      - VIRTUAL_HOST=freescout.domain.com.au
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=freescout.domain.com.au
      - LETSENCRYPT_EMAIL=sysops@domain.com.au

      - ZABBIX_HOSTNAME=freescout-app

      - DB_HOST=freescout-db
      - DB_NAME=freescout
      - DB_USER=freescout
      - DB_PASS=freescout

      - SITE_URL=https://freescout.domain.com.au
      - ADMIN_EMAIL=admin@domain.com.au
#      - ADMIN_PASS=freescout
      - ENABLE_SSL_PROXY=TRUE
      - DISPLAY_ERRORS=FALSE
      - TIMEZONE=Australia/Melbourne
    env_file:
      - .env
    networks:
      - proxy-tier
    restart: always

  freescout-db:
    image: tiredofit/mariadb
    container_name: freescout-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=freescout
      - MYSQL_USER=freescout
      - MYSQL_PASSWORD=freescout

      - ZABBIX_HOSTNAME=freescout-db
    env_file:
      - .env
    networks:
      - proxy-tier
    restart: always

  freescout-db-backup:
    image: tiredofit/db-backup
    container_name: freescout-db-backup
    links:
     - freescout-db
    volumes:
      - ./dbbackup:/backup
    environment:
      - ZABBIX_HOSTNAME=freescout-db-backup
      - DB_HOST=freescout-db
      - DB_TYPE=mariadb
      - DB_NAME=freescout
      - DB_USER=freescout
      - DB_PASS=freescout
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
      - MD5=TRUE
    env_file:
      - .env
    networks:
      - proxy-tier
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy_default
```

**Comment by BrianGilbert** [comment]
this may be related to not being able to run the freescout update..

**Comment by tiredofit** [comment]
Let's see if the update I just pushed solves it, but the log details there that there is something wrong with the client IMAP access code. Let me know.

**Comment by BrianGilbert** [comment]
Still getting the same error:

```
imap_open(): Couldn't open stream {imap.gmail.com:993/imap/ssl}. Certificate failure for imap.gmail.com: self signed certificate: /OU=No SNI provided; please fix your client./CN=invalid2.invalid; File: /www/html/overrides/Webklex/IMAP/Client.php (230) 
```

I found the following that may lead to a solution:
"You need SSL support enabled. Contact your hosting provider or recompile PHP with ssl/imap-ssl"

**Comment by BrianGilbert** [comment]
@tiredofit Disabling certificate validation gets around this error, so I'd say it's. likely an upstream issue with freescout. what do you think?

I've created an issue in freescout to try and get confirmation.

**Comment by tiredofit** [comment]
I believe this should be upstream, but I could also update ca-certificates just to make sure. Will add into the next release.

**Comment by BrianGilbert** [comment]
The upstream reply was to just disable validation
https://github.com/freescout-helpdesk/freescout/issues/302#issuecomment-517308505

Still worth updating the certs though I'd say.

**Comment by BrianGilbert** [comment]
He's confirmed validated certs should work
https://github.com/freescout-helpdesk/freescout/issues/302#issuecomment-517545031

**Comment by tiredofit** [comment]
OK, thank you.

**Comment by BrianGilbert** [comment]
@tiredofit just confirming this is still an issue with 1.0

**Comment by BrianGilbert** [comment]
I've just set up another instance and cert validation is passing (non-gmail), either way pretty sure this is an upstream issue.
