### ISSUE TITLE
Nginx 404 error

### ISSUE THREAD

**Issue by ThaStealth** [tiredofit/docker-freescout#92]
### Summary

Freescout doesn't start, Nginx returns a 404. 

Downgrading to 1.15.63 worked

### Steps to reproduce

Updated to the latest version (1.15.64)

### What is the expected *correct* behavior?

Server coming up

### Relevant logs and/or screenshots

The following log is written to the nginx/error.log:

> 2022/10/05 08:46:31 [error] 1509#1509: *1 open() "/etc/nginx/<WEBROOT>/public/storage/uploads/WLpBiEkdyduY7Hfhnzu2Slc2L.png" failed (2: No such file or directory), client: <my ip>, server: , request: "GET /storage/uploads/WLpBiEkdyduY7Hfhnzu2Slc2L.png HTTP/1.1", host: "<my domain name>"

### Environment

- Image version / tag:  1.15.64
- Host OS: Ubuntu 22.04

<details>
<summary>Any logs | docker-compose.yml</summary>
</details>

**Comment by Fma965** [comment]
I guess this is the same as what i have @tiredofit

**Comment by tiredofit** [comment]
Sorry, there was a problem in upstream image. I have fixed upstream and also changed within Freescout image as well. Please let me know if resolved.

**Comment by Fma965** [comment]
Still doesn't work

nginx: [emerg] directive "listen" is not terminated by ";" in /etc/nginx/sites.enabled/freescout.conf:3

2022-10-05.16:45:56 [STARTING] ** [php-fpm] [21] Starting php-fpm 8.1.11

2022-10-05.16:45:57 [STARTING] ** [nginx] [22] Starting nginx 1.23.1

nginx: [emerg] directive "listen" is not terminated by ";" in /etc/nginx/sites.enabled/freescout.conf:3

2022-10-05.16:45:57 [STARTING] ** [php-fpm] [22] Starting php-fpm 8.1.11

2022-10-05.16:45:58 [STARTING] ** [nginx] [23] Starting nginx 1.23.1

nginx: [emerg] directive "listen" is not terminated by ";" in /etc/nginx/sites.enabled/freescout.conf:3

**Comment by Fma965** [comment]
![image](https://user-images.githubusercontent.com/1707290/194117140-eec6a882-6157-493a-99a7-7b295064a5b1.png)

**Comment by tiredofit** [comment]
Thanks, Template tags are not working. Investigating.

**Comment by tiredofit** [comment]
How embarrassing - I had a bit of a health issue in the past few days and must have written all of this with googly eyes to get my brain to start firing properly. I found the culprit and restarting all build processes all over again. This should be under an hour to be back on track with 1.15.66

**Comment by Fma965** [comment]
No problem, thanks for looking in to it so quickly :)

**Comment by Fma965** [comment]
Still doesn't work.

![image](https://user-images.githubusercontent.com/1707290/194140950-2f3ecb6f-b771-45a4-a1d9-2dd311accdbb.png)

**Comment by Fma965** [comment]
Nope 😆  
![image](https://user-images.githubusercontent.com/1707290/194146769-c4b964aa-d620-4432-95ff-5f5d47664377.png)

**Comment by tiredofit** [comment]
ok how's about a `env | grep PHP_VERSION`   then, if it says PHP 7.X (which it should) then it would be `/etc/php7/php-fpm.conf`

**Comment by Fma965** [comment]
to confirm, tiredofit/freescout:latest is right yes?

**Comment by tiredofit** [comment]
I generally don't use :latests myself for this issue, but if that is what you are using I'll work with that easy enough!

Hang tight.

**Comment by Fma965** [comment]
:latest appears to be using php-fpm8.1 and fails with the above error, 

the folder is php81 and i don't see the directive it's complaining about 🤷

**Comment by tiredofit** [comment]
Me neither, I just tried to recreate on my end and no such thing.

````
[tiredofit/freescout:1.15.66 12:38:16 /] $ cat /etc/php81/php-fpm.conf | grep "[access|error].*log"
error_log = /www/logs/php-fpm/error.log
access.log = /www/logs/php-fpm/access.log
php_admin_value[log_errors_max_len] = 3072
````

Searching..

**Comment by Fma965** [comment]
`[tiredofit/freescout:1.15.66 19:39:21 /] $ cat /etc/php81/php-fpm.conf | grep "[access|error].*log"
; Error log file
; If it's set to "syslog", log is sent to syslogd instead of being written
; Default Value: log/php81/error.log
;error_log = log/php81/error.log
; syslog_facility is used to specify what type of program is logging the
; message. This lets syslogd specify that messages from different facilities
; See syslog(3) for possible values (ex daemon equiv LOG_DAEMON)
;syslog.facility = daemon
; syslog_ident is prepended to every message. If you have multiple FPM
;syslog.ident = php-fpm81
; Log limit on number of characters in the single line (log entry). If the
; all logged characters including message prefix and suffix if present. However
; when logging to syslog.
; Log buffering specifies if the log line is buffered which means that the
; option that can potentially improve logging performance and memory usage
; for some heavy logging scenarios. This option is ignored if logging to syslog
; used in logs and stats. There is no limitation on the number of pools which
[tiredofit/freescout:1.15.66 19:39:32 /] $ ^C
[tiredofit/freescout:1.15.66 19:39:43 /] $ `

**Comment by tiredofit** [comment]
Interesting! your configuration didn't generate it looks like.

Are you able to stop and start again just to see if we can find out more?

**Comment by Fma965** [comment]
ok so hard setting tiredofit/freescout:1.15.66 works, latest does not.

**Comment by tiredofit** [comment]
I have undocumented tags available:

````
latest
latest_php8.0
latest_php7.4
latest_php8.1
1.15.66	
1.15.66_php7.4	
1.15.66_php8.1	
1.15.66_php8.0	
````

**Comment by Fma965** [comment]
> I have undocumented tags available:
> 
> ```
> latest
> latest_php8.0
> latest_php7.4
> latest_php8.1
> 1.15.66	
> 1.15.66_php7.4	
> 1.15.66_php8.1	
> 1.15.66_php8.0	
> ```

Do you want me to try any? my "helpdesk" is pretty low traffic as most people use the forum so can start/stop it whenever pretty much

**Comment by tiredofit** [comment]
If you could that would be great! I can't seem to recreate the logging issue you just had in any of them on my Dev system (actual mirror of a prod environment).

**Comment by Fma965** [comment]
I just noticed something else in the log, didn't see it before cuz of the php spam 

sed: -e expression #1, char 26: unterminated `s' command

**Comment by Fma965** [comment]
Yeah it's working now, something in my ENV must not like :latest even though it works on older versions 🤔

**Comment by tiredofit** [comment]
Interesting. I wonder if there are some caching issues happening - I saw Github actions having problems this morning. Now onto your find with the sed command, this here is a proper bug within the freescout container initialization. Searching..

**Comment by Fma965** [comment]
If you have some way of private sending you my env i will send it to you

**Comment by tiredofit** [comment]
Not to worry, I can recreate it and I just fixed in `1.15.67` which is building as we speak.

**Comment by Fma965** [comment]
> Not to worry, I can recreate it and I just fixed in `1.15.67` which is building as we speak.

Awesome, because i realised i didn't backup my env, i only kept the important values and let the container created the rest 😆

**Comment by tiredofit** [comment]
OK! We've got new images for all PHP variants now - Hopefully we can close this chapter off after you verify?

**Comment by Fma965** [comment]
Looks good my end, but OP was reporting a different issue likely caused by the issue i reported... presumably that is also fixed though?

**Comment by tiredofit** [comment]
Yes - they were related to template tags not filling in - We'll wait for @ThaStealth to confirm good, but I believe a whole handful of issues were resolved in this issue.

**Comment by ThaStealth** [comment]
I tested it today and it seems to be fixed for me as well!
